// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/redeye/content.proto

/*
Package redeye is a generated protocol buffer package.

It is generated from these files:
	proto/redeye/content.proto
	proto/redeye/content_service.proto
	proto/redeye/model.proto
	proto/redeye/tv.proto

It has these top-level messages:
	Content
	ContentDescription
	UserGeneratedContent
	TvSeriesEpisodeContent
	MovieContent
	AdvertisementContent
	OtherContent
	CreateContentRequest
	CreateContentResponse
	GetContentRequest
	GetContentResponse
	ListContentRequest
	ListContentResponse
	UpdateContentRequest
	UpdateContentResponse
	DeleteContentRequest
	DeleteContentResponse
	Model
*/
package redeye

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
